/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'FE7(CN)'
*/

#pragma once

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct $767463F3197D627923998BA17293A2B5;
struct ClassBattleAnimationConfigData;

/* 1 */
typedef unsigned __int8 u8;

/* 2 */
typedef unsigned __int16 u16;

/* 3 */
typedef unsigned int u32;

/* 4 */
typedef unsigned __int64 u64;

/* 5 */
typedef signed __int8 s8;

/* 6 */
typedef signed __int16 s16;

/* 7 */
typedef signed int s32;

/* 8 */
typedef signed __int64 s64;

/* 9 */
typedef float f32;

/* 10 */
typedef double f64;

/* 11 */
typedef volatile u8 vu8;

/* 12 */
typedef volatile u16 vu16;

/* 13 */
typedef volatile u32 vu32;

/* 14 */
typedef volatile u64 vu64;

/* 15 */
typedef volatile s8 vs8;

/* 16 */
typedef volatile s16 vs16;

/* 17 */
typedef volatile s32 vs32;

/* 18 */
typedef volatile s64 vs64;

/* 19 */
typedef volatile f32 vf32;

/* 20 */
typedef volatile f64 vf64;

/* 21 */
struct $7283A60113E8044677CC0F5A480D9B38
{
  unsigned __int32 CpuMode : 5;
  unsigned __int32 Thumb_State : 1;
  unsigned __int32 Fiq_Disable : 1;
  unsigned __int32 Irq_Disable : 1;
  unsigned __int32 Dummy_27_8 : 20;
  unsigned __int32 V_Flag : 1;
  unsigned __int32 C_Flag : 1;
  unsigned __int32 Z_Flag : 1;
  unsigned __int32 N_Flag : 1;
};

/* 22 */
typedef struct $7283A60113E8044677CC0F5A480D9B38 PsrData;

/* 23 */
typedef volatile PsrData vPsrData;

/* 24 */
struct $91A37F3E2957D82ADBDB13DE08B6AF9D
{
  unsigned __int16 V_Blank : 1;
  unsigned __int16 H_Blank : 1;
  unsigned __int16 V_Count : 1;
  unsigned __int16 Timer0 : 1;
  unsigned __int16 Timer1 : 1;
  unsigned __int16 Timer2 : 1;
  unsigned __int16 Timer3 : 1;
  unsigned __int16 Sio : 1;
  unsigned __int16 Dma0 : 1;
  unsigned __int16 Dma1 : 1;
  unsigned __int16 Dma2 : 1;
  unsigned __int16 Dma3 : 1;
  unsigned __int16 Key : 1;
  unsigned __int16 Cassette : 1;
  unsigned __int16 Dummy_15_14 : 2;
};

/* 25 */
typedef struct $91A37F3E2957D82ADBDB13DE08B6AF9D IntrFlags;

/* 26 */
typedef volatile IntrFlags vIntrFlags;

/* 27 */
struct $9516C70BA38EC0872D54B19DE36ECDA5
{
  unsigned __int16 BgMode : 3;
  unsigned __int16 CgbMode : 1;
  unsigned __int16 Bmp_FrameNo : 1;
  unsigned __int16 Obj_H_Off : 1;
  unsigned __int16 ObjCharMapType : 1;
  unsigned __int16 Lcdc_Off : 1;
  unsigned __int16 Bg0_On : 1;
  unsigned __int16 Bg1_On : 1;
  unsigned __int16 Bg2_On : 1;
  unsigned __int16 Bg3_On : 1;
  unsigned __int16 Obj_On : 1;
  unsigned __int16 Win0_On : 1;
  unsigned __int16 Win1_On : 1;
  unsigned __int16 ObjWin_On : 1;
};

/* 28 */
typedef struct $9516C70BA38EC0872D54B19DE36ECDA5 DispCnt;

/* 29 */
typedef volatile DispCnt vDispCnt;

/* 30 */
struct $31544CC9246666AA735CF7EC61824C95
{
  unsigned __int16 V_Blank_Flag : 1;
  unsigned __int16 H_Blank_Flag : 1;
  unsigned __int16 V_Count_Flag : 1;
  unsigned __int16 V_Blank_IF_Enable : 1;
  unsigned __int16 H_Blank_IF_Enable : 1;
  unsigned __int16 V_Count_IF_Enable : 1;
  unsigned __int16 Dummy_7_6 : 2;
  u8 V_Count_Cmp;
  u8 V_Count;
  u8 Dummy_31_24;
};

/* 31 */
typedef struct $31544CC9246666AA735CF7EC61824C95 StatCnt;

/* 32 */
typedef volatile StatCnt vStatCnt;

/* 33 */
struct $52159A8D60E0E32CEF7BF8BA66C0B73D
{
  unsigned __int16 Bg_HSize : 4;
  unsigned __int16 Bg_VSize : 4;
  unsigned __int16 Obj_HSize : 4;
  unsigned __int16 Obj_VSize : 4;
};

/* 34 */
typedef struct $52159A8D60E0E32CEF7BF8BA66C0B73D MosCnt;

/* 35 */
typedef volatile MosCnt vMosCnt;

/* 36 */
struct $CE8B83EAF61832BFDC4AD2CBE418918F
{
  unsigned __int16 Pixel_1st_Bg0_On : 1;
  unsigned __int16 Pixel_1st_Bg1_On : 1;
  unsigned __int16 Pixel_1st_Bg2_On : 1;
  unsigned __int16 Pixel_1st_Bg3_On : 1;
  unsigned __int16 Pixel_1st_Obj_On : 1;
  unsigned __int16 Pixel_1st_Bd_On : 1;
  unsigned __int16 BlendMode : 2;
  unsigned __int16 Pixel_2nd_Bg0_On : 1;
  unsigned __int16 Pixel_2nd_Bg1_On : 1;
  unsigned __int16 Pixel_2nd_Bg2_On : 1;
  unsigned __int16 Pixel_2nd_Bg3_On : 1;
  unsigned __int16 Pixel_2nd_Obj_On : 1;
  unsigned __int16 Pixel_2nd_Bd_On : 1;
  unsigned __int16 Dummy_15_14 : 2;
  unsigned __int16 Value_A : 5;
  unsigned __int16 Dummy_23_21 : 3;
  unsigned __int16 Value_B : 5;
  unsigned __int16 Dummy_31_29 : 3;
  unsigned __int16 Value_Y : 5;
  unsigned __int16 Dummy_39_37 : 3;
};

/* 37 */
typedef struct $CE8B83EAF61832BFDC4AD2CBE418918F BlendCnt;

/* 38 */
typedef volatile BlendCnt vBlendCnt;

/* 39 */
struct $7A76559BC6F13ED7D19B3479300C7DD8
{
  unsigned __int16 Priority : 2;
  unsigned __int16 CharBasep : 2;
  unsigned __int16 Dummy_5_4 : 2;
  unsigned __int16 Mosaic : 1;
  unsigned __int16 ColorMode : 1;
  unsigned __int16 ScBasep : 5;
  unsigned __int16 Loop : 1;
  unsigned __int16 Size : 2;
};

/* 40 */
typedef struct $7A76559BC6F13ED7D19B3479300C7DD8 BgCnt;

/* 41 */
typedef volatile BgCnt vBgCnt;

/* 42 */
struct $5054F2BDCAEE086495E2FDC4B77F8A1D
{
  u16 H;
  u16 V;
};

/* 43 */
typedef struct $5054F2BDCAEE086495E2FDC4B77F8A1D BgOffsetCnt;

/* 44 */
typedef volatile BgOffsetCnt vBgOffsetCnt;

/* 45 */
struct $4E73AADB818178B1CCCE1798BF39A155
{
  unsigned __int16 CharNo : 10;
  unsigned __int16 HFlip : 1;
  unsigned __int16 VFlip : 1;
  unsigned __int16 Pltt : 4;
};

/* 46 */
typedef struct $4E73AADB818178B1CCCE1798BF39A155 BgScData;

/* 47 */
typedef volatile BgScData vBgScData;

/* 48 */
struct $7DE431ABFE2F7C4B13CEAB14F206B2D0
{
  s32 SrcCenterX;
  s32 SrcCenterY;
  s16 DispCenterX;
  s16 DispCenterY;
  s16 RatioX;
  s16 RatioY;
  u16 Theta;
};

/* 49 */
typedef struct $7DE431ABFE2F7C4B13CEAB14F206B2D0 BgAffineSrcData;

/* 50 */
typedef volatile BgAffineSrcData vBgAffineSrcData;

/* 51 */
struct $E5350A515B37E253D9E4937AF1ED8EBD
{
  s16 H_DiffX;
  s16 V_DiffX;
  s16 H_DiffY;
  s16 V_DiffY;
  s32 StartX;
  s32 StartY;
};

/* 52 */
typedef struct $E5350A515B37E253D9E4937AF1ED8EBD BgAffineDestData;

/* 53 */
typedef volatile BgAffineDestData vBgAffineDestData;

/* 54 */
struct $4A461261DF42FA6D587F25B4CC65DB3A
{
  unsigned __int32 VPos : 8;
  unsigned __int32 AffineMode : 2;
  unsigned __int32 ObjMode : 2;
  unsigned __int32 Mosaic : 1;
  unsigned __int32 ColorMode : 1;
  unsigned __int32 Shape : 2;
  unsigned __int32 HPos : 9;
  unsigned __int32 AffineParamNo_L : 3;
  unsigned __int32 HFlip : 1;
  unsigned __int32 VFlip : 1;
  unsigned __int32 Size : 2;
  unsigned __int16 CharNo : 10;
  unsigned __int16 Priority : 2;
  unsigned __int16 Pltt : 4;
  u16 AffineParam;
};

/* 55 */
typedef struct $4A461261DF42FA6D587F25B4CC65DB3A OamData;

/* 56 */
typedef volatile OamData vOamData;

/* 57 */
struct $9D005B2C7DEE47A2E34968395C24D475
{
  s8 SortUpDown;
  unsigned __int8 SrcPadSize : 4;
  unsigned __int8 DestPadSize : 4;
  u8 SetNum;
  u8 CheckOffset;
  void *CheckStartp;
  u32 CheckMask;
};

/* 58 */
typedef struct $9D005B2C7DEE47A2E34968395C24D475 OamSortSetParam;

/* 59 */
typedef volatile OamSortSetParam vOamSortSetParam;

/* 60 */
struct $7C6BA91EE3B7734611466E6EBDAE7514
{
  s16 RatioX;
  s16 RatioY;
  u16 Theta;
};

/* 61 */
typedef struct $7C6BA91EE3B7734611466E6EBDAE7514 ObjAffineSrcData;

/* 62 */
typedef volatile ObjAffineSrcData vObjAffineSrcData;

/* 63 */
struct $5BBA4538DBD1F793894D6EB676EE0CCA
{
  s16 H_DiffX;
  s16 V_DiffX;
  s16 H_DiffY;
  s16 V_DiffY;
};

/* 64 */
typedef struct $5BBA4538DBD1F793894D6EB676EE0CCA ObjAffineDestData;

/* 65 */
typedef volatile ObjAffineDestData vObjAffineDestData;

/* 66 */
struct $A94A44283849675D17627BB362C99BA7
{
  unsigned __int16 Red : 5;
  unsigned __int16 Green : 5;
  unsigned __int16 Blue : 5;
  unsigned __int16 Dummy_15 : 1;
};

/* 67 */
typedef struct $A94A44283849675D17627BB362C99BA7 PlttData;

/* 68 */
typedef volatile PlttData vPlttData;

/* 69 */
struct $329E313DB0C4CF2DB81CC8221EDAC9AF
{
  unsigned __int8 Bg0_On : 1;
  unsigned __int8 Bg1_On : 1;
  unsigned __int8 Bg2_On : 1;
  unsigned __int8 Bg3_On : 1;
  unsigned __int8 Obj_On : 1;
  unsigned __int8 Blend_On : 1;
  unsigned __int8 Dummy_7_6 : 2;
};

/* 70 */
typedef struct $329E313DB0C4CF2DB81CC8221EDAC9AF WindCnt;

/* 71 */
typedef volatile WindCnt vWindCnt;

/* 72 */
struct $3DFC682C7973B4E1F3A97ACBD4400412
{
  unsigned __int8 So1_Level : 3;
  unsigned __int8 So1_Vin_On : 1;
  unsigned __int8 So2_Level : 3;
  unsigned __int8 So2_Vin_On : 1;
  unsigned __int8 So1_Sound1_On : 1;
  unsigned __int8 So1_Sound2_On : 1;
  unsigned __int8 So1_Sound3_On : 1;
  unsigned __int8 So1_Sound4_On : 1;
  unsigned __int8 So2_Sound1_On : 1;
  unsigned __int8 So2_Sound2_On : 1;
  unsigned __int8 So2_Sound3_On : 1;
  unsigned __int8 So2_Sound4_On : 1;
  unsigned __int8 Sound_1_4_Mix : 2;
  unsigned __int8 DirectA_Mix : 1;
  unsigned __int8 DirectB_Mix : 1;
  unsigned __int8 Dummy_23_20 : 4;
  unsigned __int8 So1_DirectA_On : 1;
  unsigned __int8 So2_DirectA_On : 1;
  unsigned __int8 DirectA_Timer : 1;
  unsigned __int8 FifoA_Reset : 1;
  unsigned __int8 So1_DirectB_On : 1;
  unsigned __int8 So2_DirectB_On : 1;
  unsigned __int8 DirectB_Timer : 1;
  unsigned __int8 FifoB_Reset : 1;
  unsigned __int8 Sound1_On : 1;
  unsigned __int8 Sound2_On : 1;
  unsigned __int8 Sound3_On : 1;
  unsigned __int8 Sound4_On : 1;
  unsigned __int8 Dummy_38_36 : 3;
  unsigned __int8 Sound_1_4_On : 1;
  u8 Dummy_47_40;
  u16 Dummy_63_48;
  unsigned __int16 BiasLevel : 10;
  unsigned __int16 Dummy_77_74 : 4;
  unsigned __int16 OutFrequency : 2;
};

/* 73 */
typedef struct $3DFC682C7973B4E1F3A97ACBD4400412 SoundCnt;

/* 74 */
typedef volatile SoundCnt vSoundCnt;

/* 75 */
struct $E56FB425D8D529D55B3383F5A2C6D966
{
  unsigned __int8 SweepShift : 3;
  unsigned __int8 SweepUpDownt : 1;
  unsigned __int8 SweepTime : 3;
  unsigned __int8 Dummy_7 : 1;
  u8 Dummy_15_8;
  unsigned __int8 Counts : 6;
  unsigned __int8 Duty : 2;
  unsigned __int8 EnvSteps : 3;
  unsigned __int8 EnvUp_Down : 1;
  unsigned __int8 EnvInitData : 4;
  unsigned __int16 Frequency : 11;
  unsigned __int16 Dummy_45_43 : 3;
  unsigned __int16 Counter_On : 1;
  unsigned __int16 Start : 1;
};

/* 76 */
typedef struct $E56FB425D8D529D55B3383F5A2C6D966 Sound1Cnt;

/* 77 */
typedef volatile Sound1Cnt vSound1Cnt;

/* 78 */
struct $79DCBB646E755A1B7DD622045DD476A2
{
  unsigned __int8 Counts : 6;
  unsigned __int8 Duty : 2;
  unsigned __int8 EnvSteps : 3;
  unsigned __int8 EnvUp_Down : 1;
  unsigned __int8 EnvInitData : 4;
  u16 Dummy_31_16;
  unsigned __int16 Frequency : 11;
  unsigned __int16 Dummy_45_43 : 3;
  unsigned __int16 Counter_On : 1;
  unsigned __int16 Start : 1;
};

/* 79 */
typedef struct $79DCBB646E755A1B7DD622045DD476A2 Sound2Cnt;

/* 80 */
typedef volatile Sound2Cnt vSound2Cnt;

/* 81 */
struct $AF8AE87A46720E695E81B3979DE696B9
{
  unsigned __int8 Dummy_6_0 : 5;
  unsigned __int8 Connect : 1;
  unsigned __int8 Bank : 1;
  unsigned __int8 On : 1;
  u8 Dummy_15_8;
  u8 Counts;
  unsigned __int8 Dummy_28_24 : 5;
  unsigned __int8 OutputLevel : 3;
  unsigned __int16 Frequency : 11;
  unsigned __int16 Dummy_45_43 : 3;
  unsigned __int16 Counter_On : 1;
  unsigned __int16 Start : 1;
};

/* 82 */
typedef struct $AF8AE87A46720E695E81B3979DE696B9 Sound3Cnt;

/* 83 */
typedef volatile Sound3Cnt vSound3Cnt;

/* 84 */
struct $2A6489154C1E65D49CC297839CFBFBFC
{
  unsigned __int8 Counts : 6;
  unsigned __int8 Dummy_15_14 : 2;
  unsigned __int8 EnvSteps : 3;
  unsigned __int8 EnvUp_Down : 1;
  unsigned __int8 EnvInitData : 4;
  u16 Dummy_31_16;
  unsigned __int8 PreScaler : 3;
  unsigned __int8 PolySteps : 1;
  unsigned __int8 PolyShift : 4;
  unsigned __int8 Dummy45_40 : 6;
  unsigned __int8 Counter_On : 1;
  unsigned __int8 Start : 1;
};

/* 85 */
typedef struct $2A6489154C1E65D49CC297839CFBFBFC Sound4Cnt;

/* 86 */
typedef volatile Sound4Cnt vSound4Cnt;

/* 87 */
struct $F566D4A8FD89F658A59DB3470F891C8F
{
  unsigned __int16 Sck_I_O : 1;
  unsigned __int16 Sck : 1;
  unsigned __int16 AckRecv : 1;
  unsigned __int16 AckSend : 1;
  unsigned __int16 Dummy_6_4 : 3;
  unsigned __int16 Enable : 1;
  unsigned __int16 Dummy_11_8 : 4;
  unsigned __int16 Mode : 2;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 Dammy_15 : 1;
  u8 Data;
  u8 Dummy_31_24;
};

/* 88 */
typedef struct $F566D4A8FD89F658A59DB3470F891C8F SioNormalCnt;

/* 89 */
typedef volatile SioNormalCnt vSioNormalCnt;

/* 90 */
struct $507D2A26AC84DAE830429A6CEDFFD3E9
{
  unsigned __int16 BaudRate : 2;
  unsigned __int16 SI : 1;
  unsigned __int16 SD : 1;
  unsigned __int16 ID : 2;
  unsigned __int16 Error : 1;
  unsigned __int16 Enable : 1;
  unsigned __int16 Dummy_11_8 : 4;
  unsigned __int16 Mode : 2;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 Dammy_15 : 1;
  u16 Data;
};

/* 91 */
typedef struct $507D2A26AC84DAE830429A6CEDFFD3E9 SioMultiCnt;

/* 92 */
typedef volatile SioMultiCnt vSioMultiCnt;

/* 93 */
struct $DD1FA034EB3F51238B8302AA56CC2D77
{
  unsigned __int16 BaudRate : 2;
  unsigned __int16 Cts_Enable : 1;
  unsigned __int16 ParitySelect : 1;
  unsigned __int16 TransDataFull : 1;
  unsigned __int16 RecvDataEmpty : 1;
  unsigned __int16 Error : 1;
  unsigned __int16 Length : 1;
  unsigned __int16 Fifo_Enable : 1;
  unsigned __int16 Parity_Enable : 1;
  unsigned __int16 Trans_Enable : 1;
  unsigned __int16 Recv_Enable : 1;
  unsigned __int16 Mode : 2;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 Dammy_15 : 1;
  u8 Data;
  u8 Dummy_31_24;
};

/* 94 */
typedef struct $DD1FA034EB3F51238B8302AA56CC2D77 SioUartCnt;

/* 95 */
typedef volatile SioUartCnt vSioUartCnt;

/* 96 */
struct $48A56D63A3BF97C299E97A05D8AA3F67
{
  unsigned __int8 IF_Reset : 1;
  unsigned __int8 IF_Recv : 1;
  unsigned __int8 IF_Send : 1;
  unsigned __int8 Dummy_5_3 : 3;
  unsigned __int8 IF_Enable : 1;
  unsigned __int8 Dummy_7 : 1;
};

/* 97 */
typedef struct $48A56D63A3BF97C299E97A05D8AA3F67 JoyCnt;

/* 98 */
typedef volatile JoyCnt vJoyCnt;

/* 99 */
struct $19C09E2038D19DC1274172D364FD1CB1
{
  unsigned __int8 Dummy_0 : 1;
  unsigned __int8 Recv : 1;
  unsigned __int8 Dummy_2 : 1;
  unsigned __int8 Send : 1;
  unsigned __int8 Flags : 2;
  unsigned __int8 Dummy_7_6 : 2;
};

/* 100 */
typedef struct $19C09E2038D19DC1274172D364FD1CB1 JoyStat;

/* 101 */
typedef volatile JoyStat vJoyStat;

/* 102 */
struct $25E4905B2AAB90B21832F1C7A55221AD
{
  unsigned __int8 SC : 1;
  unsigned __int8 SD : 1;
  unsigned __int8 SI : 1;
  unsigned __int8 SO : 1;
  unsigned __int8 SC_I_O : 1;
  unsigned __int8 SD_I_O : 1;
  unsigned __int8 SI_I_O : 1;
  unsigned __int8 SO_I_O : 1;
  unsigned __int8 IF_Enable : 1;
  unsigned __int8 Dummy_13_9 : 5;
  unsigned __int8 SioModeMaster : 2;
};

/* 103 */
typedef struct $25E4905B2AAB90B21832F1C7A55221AD RCnt;

/* 104 */
typedef volatile RCnt vRCnt;

/* 105 */
struct $36389E581391F010DA50195330B0F105
{
  u16 Count;
  unsigned __int16 Dummy_21_16 : 5;
  unsigned __int16 DestpCnt : 2;
  unsigned __int16 SrcpCnt : 2;
  unsigned __int16 ContinuousON : 1;
  unsigned __int16 BusSize : 1;
  unsigned __int16 DataRequest : 1;
  unsigned __int16 Timming : 2;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 Enable : 1;
};

/* 106 */
typedef struct $36389E581391F010DA50195330B0F105 DmaCnt;

/* 107 */
typedef volatile DmaCnt vDmaCnt;

/* 108 */
struct $B2C8AA5841AE2D0D5BFC892A5839C81D
{
  u16 Count;
  unsigned __int16 PreScaler : 2;
  unsigned __int16 Connect : 1;
  unsigned __int16 Dummy_5_3 : 3;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 Enable : 1;
  unsigned __int16 Dummy_15_8 : 8;
};

/* 109 */
typedef struct $B2C8AA5841AE2D0D5BFC892A5839C81D TimerCnt;

/* 110 */
typedef volatile TimerCnt vTimerCnt;

/* 111 */
struct $37D02F90570DC221CBF6DB42A312520E
{
  unsigned __int16 A : 1;
  unsigned __int16 B : 1;
  unsigned __int16 Select : 1;
  unsigned __int16 Start : 1;
  unsigned __int16 Plus_R : 1;
  unsigned __int16 Plus_L : 1;
  unsigned __int16 Plus_U : 1;
  unsigned __int16 Plus_D : 1;
  unsigned __int16 R : 1;
  unsigned __int16 L : 1;
  unsigned __int16 Dummy_15_10 : 6;
};

/* 112 */
typedef struct $37D02F90570DC221CBF6DB42A312520E KeyData;

/* 113 */
typedef volatile KeyData vKeyData;

/* 114 */
struct $A699298924A979DDFBF7C0C883327870
{
  unsigned __int16 Sel_A : 1;
  unsigned __int16 Sel_B : 1;
  unsigned __int16 Sel_Select : 1;
  unsigned __int16 Sel_Start : 1;
  unsigned __int16 Sel_Plus_R : 1;
  unsigned __int16 Sel_Plus_L : 1;
  unsigned __int16 Sel_Plus_U : 1;
  unsigned __int16 Sel_Plus_D : 1;
  unsigned __int16 Sel_R : 1;
  unsigned __int16 Sel_L : 1;
  unsigned __int16 Dummy_13_10 : 4;
  unsigned __int16 IF_Enable : 1;
  unsigned __int16 IntrType : 1;
};

/* 115 */
typedef struct $A699298924A979DDFBF7C0C883327870 KeyCnt;

/* 116 */
typedef volatile KeyCnt vKeyCnt;

/* 117 */
struct $2768D0B151B638E8D14143B1CF133B5F
{
  unsigned __int16 Sram : 2;
  unsigned __int16 Rom0_1st : 2;
  unsigned __int16 Rom0_2nd : 1;
  unsigned __int16 Rom1_1st : 2;
  unsigned __int16 Rom1_2nd : 1;
  unsigned __int16 Rom2_1st : 2;
  unsigned __int16 Rom2_2nd : 1;
  unsigned __int16 OutClock : 2;
  unsigned __int16 Dummy_13 : 1;
  unsigned __int16 PrefetchEnale : 1;
  unsigned __int16 CassetteType : 1;
};

/* 118 */
typedef struct $2768D0B151B638E8D14143B1CF133B5F CstWaitCnt;

/* 119 */
typedef volatile CstWaitCnt vCstWaitCnt;

/* 120 */
struct $FF47844B25506FA8A313B310A934E9E9
{
  u16 SrcNum;
  u8 SrcBitNum;
  u8 DestBitNum;
  unsigned __int32 DestOffset : 31;
  unsigned __int32 DestOffset0_On : 1;
};

/* 121 */
typedef struct $FF47844B25506FA8A313B310A934E9E9 BitUnPackParam;

/* 122 */
typedef volatile BitUnPackParam vBitUnPackParam;

/* 123 */
struct _6CCode
{
  u16 code;
  u16 sarg;
  void *larg;
};

/* 124 */
struct _6CStruct
{
  struct _6CCode *start;
  struct _6CCode *cursor;
  int (__cdecl *destructor)(int);
  int (__cdecl *loop)(int);
  char *name;
  struct _6CStruct *parent;
  struct _6CStruct *firstChild;
  struct _6CStruct *previous;
  struct _6CStruct *next;
  u16 sleepTimer;
  u8 userVal;
  u8 bitfield;
  u8 blockCounter;
  u8 userSpace[67];
};

/* 125 */
struct eventHandler
{
  int (__fastcall *func)(int);
  int codeLen;
};

/* 126 */
struct $6E845075146DF23E2FDB980B488FD3AD
{
  u16 type;
  u16 stat;
  u32 freq;
  u32 loop;
  u32 size;
  s8 data[1];
};

/* 127 */
typedef struct $6E845075146DF23E2FDB980B488FD3AD WaveData;

/* 128 */
struct $D9264090E336213B139C0C33CD7B8846
{
  u8 typ;
  u8 key;
  u8 len;
  u8 p_s;
  WaveData *wav;
  u8 att;
  u8 dec;
  u8 sus;
  u8 rel;
};

/* 129 */
typedef struct $D9264090E336213B139C0C33CD7B8846 ToneData;

/* 130 */
struct $2BF4778093F23A6BF65C3C20F359F9FE
{
  u32 typ;
  ToneData *ta;
  u8 *st;
};

/* 131 */
typedef struct $2BF4778093F23A6BF65C3C20F359F9FE SplitTone;

/* 132 */
union $401D13579C146D6819A9910C7366A0C0
{
  ToneData t;
  SplitTone s;
};

/* 133 */
typedef union $401D13579C146D6819A9910C7366A0C0 ToneDataArr;

/* 134 */
struct $BAA59F26689A65E5E53CA506FB0ACC80
{
  u8 sf;
  u8 ty;
  u8 rv;
  u8 lv;
  u8 at;
  u8 de;
  u8 su;
  u8 re;
  u8 r1[24];
  u32 fr;
  WaveData *wp;
  u32 r3[6];
};

/* 135 */
typedef struct $BAA59F26689A65E5E53CA506FB0ACC80 SoundChannel;

/* 136 */
struct $790FD5479BEDFD34ECAC3FCFAC858DD9
{
  u32 r1;
  vu8 DmaCount;
  u8 reverb;
  u8 maxchn;
  u8 masvol;
  u8 freq;
  u8 mode;
  u8 r2[6];
  u32 r3[16];
  SoundChannel vchn[12];
  s8 pcmbuf[3168];
};

/* 137 */
typedef struct $790FD5479BEDFD34ECAC3FCFAC858DD9 SoundArea;

/* 138 */
struct $1E3C838F69E0989D5898CF13AEEFE8FA
{
  u8 trks;
  u8 blks;
  u8 prio;
  u8 rvrb;
  ToneData *tone;
  u8 *part[1];
};

/* 139 */
typedef struct $1E3C838F69E0989D5898CF13AEEFE8FA SongHeader;

/* 140 */
struct $A0042D557EEC813DC30543E627B3E567
{
  SongHeader *song;
  u32 stat;
  u8 mtrk;
  u8 prio;
  u8 d1[2];
  u32 clock;
  u8 d2[48];
};

/* 141 */
typedef struct $A0042D557EEC813DC30543E627B3E567 MusicPlayerArea;

/* 142 */
struct $3D83CF10FF1970CA8F619DECEE55AE09
{
  u8 d[80];
};

/* 143 */
typedef struct $3D83CF10FF1970CA8F619DECEE55AE09 MusicPlayerTrack;

/* 144 */
struct $323203A5F3BF5E1768C5008C2ED9F78B
{
  u8 ch1[64];
  u8 ch2[64];
  u8 ch3[64];
  u8 ch4[64];
};

/* 145 */
typedef struct $323203A5F3BF5E1768C5008C2ED9F78B CgbChannels;

/* 146 */
struct $35787D2F5E17080DB61284504B77DD6D
{
  MusicPlayerArea *ma;
  MusicPlayerTrack *ta;
  u32 tn;
};

/* 147 */
typedef struct $35787D2F5E17080DB61284504B77DD6D MPlayTable;

/* 148 */
struct $CE43CAFF55226A0089912C26CCDD3F4F
{
  SongHeader *so;
  u16 ms;
  u16 me;
};

/* 149 */
typedef struct $CE43CAFF55226A0089912C26CCDD3F4F SongTable;

/* 150 */
struct $BDE02B8B9A36D67F87133F0A6AA5C700
{
  char identifier[12];
  int (*sectionOffset)[];
  void *event;
  void *oamR2L;
  void *oamL2R;
  void *palGroup;
};

/* 151 */
typedef struct $767463F3197D627923998BA17293A2B5 BattleAnimation;

/* 154 */
struct $767463F3197D627923998BA17293A2B5
{
  char identifier[12];
  int *sectionOffset;
  void *event;
  void *oamR2L;
  void *oamL2R;
  void *palGroup;
};

/* 152 */
struct $0B4006E68FB3109F02FF76DE2B951D07
{
  char identifier[12];
  void *pal;
};

/* 153 */
typedef struct $0B4006E68FB3109F02FF76DE2B951D07 CharacterBattlePal;

/* 155 */
enum $AB35093F1CA921872F0DB78CD08EF38F
{
  FE7BABank = 0x0,
};

/* 156 */
struct ais
{
  u16 state;
  s16 XOffset;
  s16 YOffset;
  u16 delayCountdown;
  u16 OBJAttr2Base;
  u16 unk_A;
  u16 unk_C;
  u16 unk_E;
  u16 unk_10;
  u8 modeX;
  u8 frameID;
  u8 C85IDBufferIndex;
  u8 C85IDBuffer[11];
  u32 *nextCmd;
  u32 *lastCmd;
  void *sheet;
  void *sheetBuffer;
  void *OAMInfoBuffer;
  struct ais *parent;
  struct ais *child;
  void *currentOAMInfo;
  u32 unk_40;
  u32 unk_44;
};

/* 157 */
typedef struct ais AnimationInterpreter;

/* 158 */
struct $F100BF5813BF6C0E9257EF93188C3489
{
  u16 type;
  u16 state;
  struct _6CStruct *ctx;
  u32 unk_8;
  AnimationInterpreter *AIS;
};

/* 159 */
typedef struct $F100BF5813BF6C0E9257EF93188C3489 SpecialAnimationEffectInfo;

/* 160 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 161 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 162 */
typedef __n64 int8x8_t;

/* 163 */
typedef __n64 uint8x8_t;

/* 164 */
typedef __n64 int16x4_t;

/* 165 */
typedef __n64 int32x2_t;

/* 166 */
typedef __n64 uint16x4_t;

/* 167 */
typedef __n64 uint32x2_t;

/* 168 */
typedef __n128 int8x16_t;

/* 169 */
typedef __n128 int16x8_t;

/* 170 */
typedef __n128 int32x4_t;

/* 171 */
typedef __n128 int64x2_t;

/* 172 */
typedef __n128 uint8x16_t;

/* 173 */
typedef __n128 uint16x8_t;

/* 174 */
typedef __n128 uint32x4_t;

/* 175 */
typedef __n128 uint64x2_t;

/* 176 */
typedef __n64 poly8x8_t;

/* 177 */
typedef __n64 poly16x4_t;

/* 178 */
typedef __n128 poly16x8_t;

/* 179 */
typedef __n128 poly8x16_t;

/* 180 */
typedef __n64 float32x2_t;

/* 181 */
typedef __n128 float32x4_t;

/* 182 */
typedef __n128 float64x2_t;

/* 183 */
typedef __n128 poly128_t;

/* 184 */
typedef void **va_list;

/* 185 */
enum saveslot
{
  Saveslot1 = 0x0,
  Saveslot2 = 0x1,
  Saveslot3 = 0x2,
  SuspendBackup = 0x3,
  Suspend = 0x4,
  LinkArena = 0x5,
  SaveEmpty = 0x6,
};

/* 186 */
typedef u16 TextID;

/* 187 */
typedef u8 ClassID;

/* 188 */
typedef u8 CharacterID;

/* 189 */
typedef u8 ItemID;

/* 190 */
typedef u16 AnimationID;

/* 191 */
typedef u8 IconID;

/* 192 */
typedef u16 PortraitID;

/* 193 */
struct WeaponStatBonusInfo
{
  s8 hp;
  s8 atk;
  s8 skl;
  s8 spd;
  s8 def;
  s8 res;
  s8 luk;
  s8 mov;
  s8 con;
  s8 unk_9;
  s8 unk_A;
  s8 unk_B;
};

/* 194 */
typedef struct WeaponStatBonusInfo WeaponStatBonus;

/* 195 */
struct SupportDataConfig
{
  CharacterID person[7];
  u8 favorInitial[7];
  u8 favorGrowth[7];
  u8 supportNumber;
  u16 pad_16;
};

/* 196 */
typedef struct SupportDataConfig SupportData;

/* 197 */
struct CharacterInfo
{
  TextID name;
  TextID description;
  CharacterID id;
  ClassID m_class;
  PortraitID portrait;
  u8 miniPortrait;
  u8 affinity;
  u8 sortID;
  s8 baseLv;
  s8 baseStr;
  s8 baseSkl;
  s8 baseSpd;
  s8 baseDef;
  s8 baseRes;
  s8 baseLuk;
  s8 baseConBonus;
  u8 levelSword;
  u8 levelLance;
  u8 levelAxe;
  u8 levelBow;
  u8 levelStaff;
  u8 levelAnima;
  u8 levelLight;
  u8 levelDark;
  u8 growthHp;
  u8 growthStr;
  u8 growthSkl;
  u8 growthSpd;
  u8 growthDef;
  u8 growthRes;
  u8 growthLuk;
  u8 paletteIdUnpromoted;
  u8 paletteIdPromoted;
  u8 battleAnimationIdUnpromoted;
  u8 battleAnimationIdPromoted;
  u8 pad_27;
  unsigned __int8 ability_mountedAid : 1;
  unsigned __int8 ability_moveAgain : 1;
  unsigned __int8 ability_steal : 1;
  unsigned __int8 ability_theifKey : 1;
  unsigned __int8 ability_dance : 1;
  unsigned __int8 ability_play : 1;
  unsigned __int8 ability_criticalBonus : 1;
  unsigned __int8 ability_ballista : 1;
  unsigned __int8 ability_promoted : 1;
  unsigned __int8 ability_supplyDepot : 1;
  unsigned __int8 ability_mountedIcon : 1;
  unsigned __int8 ability_dragonKnightIcon : 1;
  unsigned __int8 ability_pegasusKnightIcon : 1;
  unsigned __int8 ability_lord : 1;
  unsigned __int8 ability_female : 1;
  unsigned __int8 ability_boss : 1;
  unsigned __int8 ability_unusedWeaponLock : 1;
  unsigned __int8 ability_WoDaoWeaponLock : 1;
  unsigned __int8 ability_dragonStoneWeaponLock : 1;
  unsigned __int8 ability_morph : 1;
  unsigned __int8 ability_preventControl : 1;
  unsigned __int8 ability_pegasusTriangleAttack : 1;
  unsigned __int8 ability_armorTriangleAttack : 1;
  unsigned __int8 ability_forbidden : 1;
  unsigned __int8 ability_noExp : 1;
  unsigned __int8 ability_lethality : 1;
  unsigned __int8 ability_magicSeal : 1;
  unsigned __int8 ability_dropLastItem : 1;
  unsigned __int8 ability_EliwoodWeaponLock : 1;
  unsigned __int8 ability_HectorWeaponLock : 1;
  unsigned __int8 ability_LynWeaponLock : 1;
  unsigned __int8 ability_AthosWeaponLock : 1;
  SupportData *support;
  u8 dialogueId;
  u8 pad_31;
  u16 pad_32;
};

/* 198 */
typedef struct CharacterInfo Character;

/* 199 */
struct ItemDataInfo
{
  ItemID item;
  u8 number;
};

/* 200 */
typedef struct ItemDataInfo ItemData;

/* 206 */
enum Class
{
  ClassGorgonEgg = 0x34,
  ClassNecromancer = 0x4F,
  ClassPhantom = 0x51,
  ClassGorgonEgg2 = 0x62,
  ClassDemonKing = 0x66,
};

/* 201 */
struct UnitDataInWRAM
{
  Character *character;
  Class *m_class;
  u8 lv;
  u8 exp;
  u8 unk_A;
  u8 deployNumber;
  u8 actionState;
  unsigned __int8 unk_flags_D_0_3 : 4;
  unsigned __int8 dropItem : 1;
  unsigned __int8 growthPlus : 1;
  unsigned __int8 unk_flags_D_6_7 : 2;
  u8 unk_E;
  u8 unk_F;
  u8 PositionX;
  u8 PositionY;
  s8 maxHp;
  s8 hp;
  s8 str;
  s8 skl;
  s8 spd;
  s8 def;
  s8 res;
  s8 luk;
  s8 conBonus;
  u8 aidUnitNumber;
  u8 unk_1C;
  s8 movBonus;
  ItemData items[5];
  u8 levelSword;
  u8 levelLance;
  u8 levelAxe;
  u8 levelBow;
  u8 levelStaff;
  u8 levelAnima;
  u8 levelLight;
  u8 levelDark;
  unsigned __int8 stateType : 4;
  unsigned __int8 stateTurn : 4;
  unsigned __int8 sightBonus : 4;
  unsigned __int8 resBonus : 4;
  u8 levelSupport[7];
  unsigned __int8 unlockSupport1 : 1;
  unsigned __int8 unlockSupport2 : 1;
  unsigned __int8 unlockSupport3 : 1;
  unsigned __int8 unlockSupport4 : 1;
  unsigned __int8 unlockSupport5 : 1;
  unsigned __int8 unlockSupport6 : 1;
  unsigned __int8 unlockSupport7 : 1;
  unsigned __int8 unlockSupport8 : 1;
  u8 unk_3A[6];
  unsigned __int8 AI_healing : 3;
  unsigned __int8 AI_targeting : 5;
  u8 AI_retreat;
  u8 AI_action;
  u8 AI_action_counter;
  u8 AI_movement;
  u8 AI_movement_counter;
  u8 unk_46[2];
};

/* 205 */
typedef struct ClassBattleAnimationConfigData ClassBattleAnimationConfig;

/* 202 */
struct ClassInfo
{
  TextID name;
  TextID description;
  ClassID id;
  ClassID promote;
  u8 mapSprite;
  u8 walkingSpeed;
  PortraitID classCard;
  u8 unk_A;
  s8 baseHp;
  s8 baseStr;
  s8 baseSkl;
  s8 baseSpd;
  s8 baseDef;
  s8 baseRes;
  s8 baseCon;
  s8 baseMov;
  s8 maxHp;
  s8 maxStr;
  s8 maxSkl;
  s8 maxSpd;
  s8 maxDef;
  s8 maxRes;
  s8 maxCon;
  u8 relativePower;
  s8 growthHp;
  s8 growthStr;
  s8 growthSkl;
  s8 growthSpd;
  s8 growthDef;
  s8 growthRes;
  s8 growthCon;
  s8 CCBonusHp;
  s8 CCBonusStr;
  s8 CCBonusSkl;
  s8 CCBonusSpd;
  s8 CCBonusDef;
  s8 CCBonusRes;
  unsigned __int8 ability_mountedAid : 1;
  unsigned __int8 ability_moveAgain : 1;
  unsigned __int8 ability_steal : 1;
  unsigned __int8 ability_theifKey : 1;
  unsigned __int8 ability_dance : 1;
  unsigned __int8 ability_play : 1;
  unsigned __int8 ability_criticalBonus : 1;
  unsigned __int8 ability_ballista : 1;
  unsigned __int8 ability_promoted : 1;
  unsigned __int8 ability_supplyDepot : 1;
  unsigned __int8 ability_mountedIcon : 1;
  unsigned __int8 ability_dragonKnightIcon : 1;
  unsigned __int8 ability_pegasusKnightIcon : 1;
  unsigned __int8 ability_lord : 1;
  unsigned __int8 ability_female : 1;
  unsigned __int8 ability_boss : 1;
  unsigned __int8 ability_unusedWeaponLock : 1;
  unsigned __int8 ability_WoDaoWeaponLock : 1;
  unsigned __int8 ability_dragonStoneWeaponLock : 1;
  unsigned __int8 ability_morph : 1;
  unsigned __int8 ability_preventControl : 1;
  unsigned __int8 ability_pegasusTriangleAttack : 1;
  unsigned __int8 ability_armorTriangleAttack : 1;
  unsigned __int8 ability_forbidden : 1;
  unsigned __int8 ability_noExp : 1;
  unsigned __int8 ability_lethality : 1;
  unsigned __int8 ability_magicSeal : 1;
  unsigned __int8 ability_dropLastItem : 1;
  unsigned __int8 ability_EliwoodWeaponLock : 1;
  unsigned __int8 ability_HectorWeaponLock : 1;
  unsigned __int8 ability_LynWeaponLock : 1;
  unsigned __int8 ability_AthosWeaponLock : 1;
  u8 levelSword;
  u8 levelLance;
  u8 levelAxe;
  u8 levelBow;
  u8 levelStaff;
  u8 levelAnima;
  u8 levelLight;
  u8 levelDark;
  ClassBattleAnimationConfig *battleAnimationConf;
  u8 *movementCost;
  u8 *movementCostRain;
  u8 *movementCostSnow;
  u8 *terrainBonusDef;
  u8 *terrainBonusAvoid;
  u8 *terrainBonusRes;
  u8 *unk_ptr_50;
};

/* 204 */
/*union ClassBattleAnimationConfigData::$27B3932663C0CF887A9B4C869B288CFC
{
  u8 weaponType;
  ItemID weaponID;
};*/

/* 203 */
struct ClassBattleAnimationConfigData
{
  union
  {
    u8 weaponType;
    ItemID weaponID;
  };
  u8 isWeaponID;
  AnimationID animation;
};

/* 207 */
typedef struct UnitDataInWRAM Unit;

/* 208 */
struct ItemInfo
{
  TextID name;
  TextID description;
  TextID useDescription;
  ItemID id;
  u8 category;
  unsigned __int8 isWeapon : 1;
  unsigned __int8 isMagic : 1;
  unsigned __int8 isStaff : 1;
  unsigned __int8 isIndestructible : 1;
  unsigned __int8 isUnsellable : 1;
  unsigned __int8 isBrave : 1;
  unsigned __int8 isSpell : 1;
  unsigned __int8 isUncounterable : 1;
  unsigned __int8 isReverse : 1;
  unsigned __int8 isUnrepairable : 1;
  unsigned __int8 dragonStoneWPLock : 1;
  unsigned __int8 unusedWPLock : 1;
  unsigned __int8 swordWPLock : 1;
  unsigned __int8 unknownAbility2 : 1;
  unsigned __int8 flierTalisman : 1;
  unsigned __int8 CRTTalisman : 1;
  unsigned __int8 isUnusable : 1;
  unsigned __int8 isLunar : 1;
  unsigned __int8 EliwoodWPLock : 1;
  unsigned __int8 HectorWPLock : 1;
  unsigned __int8 LynWPLock : 1;
  unsigned __int8 AthosWPLock : 1;
  unsigned __int8 unknownAbility4 : 1;
  unsigned __int8 unknownAbility5 : 1;
  unsigned __int8 unknownAbility6 : 1;
  unsigned __int8 unknownAbility7 : 1;
  unsigned __int8 unknownAbility8 : 1;
  unsigned __int8 unknownAbility9 : 1;
  unsigned __int8 unknownAbility10 : 1;
  unsigned __int8 unknownAbility11 : 1;
  unsigned __int8 unknownAbility12 : 1;
  unsigned __int8 unknownAbility13 : 1;
  WeaponStatBonus *pStatBonus;
  ClassID *pEffectivenessClassList;
  u8 durability;
  u8 power;
  u8 hit;
  u8 WT;
  u8 CRT;
  unsigned __int8 minRange : 4;
  unsigned __int8 maxRange : 4;
  u16 cost;
  u8 rank;
  IconID icon;
  u8 useEffect;
  u8 WPEffect;
  u8 WPEXP;
  u8 unk_21;
  u8 unk_22;
  u8 unk_23;
};

/* 209 */
enum Item
{
  ItemLightBrand = 0x10,
  ItemRuneSword = 0x11,
  ItemChestKey = 0x69,
  ItemDoorKey = 0x6A,
  ItemLockpick = 0x6B,
  ItemMemberCard = 0x72,
  Item5ChestKey = 0x79,
  ItemFillasMight = 0x7D,
  ItemSetsLitany = 0x80,
  ItemWindSword = 0xA1,
  ItemNightmare = 0xA6,
  ItemStone = 0xB5,
};

/* 210 */
struct SaveDataHeader
{
  u32 magicA;
  u16 magicB;
  u8 saveType;
  u8 pad_7;
  u16 sramOffset;
  u16 sramSize;
  u32 checksum;
};

/* 211 */
typedef struct SaveDataHeader SaveHeader;

/* 212 */
struct UnitDataInSave
{
  unsigned __int32 profession : 7;
  unsigned __int32 lv : 5;
  unsigned __int32 exp : 7;
  unsigned __int32 posX : 6;
  unsigned __int32 posY : 6;
  unsigned __int32 ifDead : 1;
  unsigned __int32 ifNotDeployed : 1;
  unsigned __int32 ifSoloAnimation1 : 1;
  unsigned __int32 ifSoloAnimation2 : 1;
  unsigned __int32 ifGrowRateUp : 1;
  unsigned __int32 ifUnk_1 : 1;
  unsigned __int32 ifUnk_2 : 1;
  unsigned __int32 ifNotDeployedInPreviousChap : 1;
  unsigned __int32 unk_3 : 5;
  unsigned __int32 maxHp : 6;
  unsigned __int32 pow : 5;
  unsigned __int32 skl : 5;
  unsigned __int32 spd_hi : 1;
  unsigned __int32 def : 5;
  unsigned __int32 res : 5;
  unsigned __int32 luk : 5;
  unsigned __int32 conBonus : 5;
  unsigned __int32 movBonus : 5;
  unsigned __int32 item_1_id_lo : 6;
  unsigned __int32 item_1_id_hi : 2;
  unsigned __int32 item_1_number : 6;
  unsigned __int32 item_2_id : 8;
  unsigned __int32 item_2_number : 6;
  unsigned __int32 item_3_id : 8;
  unsigned __int32 item_3_number_lo : 2;
  unsigned __int32 item_3_number_hi : 4;
  unsigned __int32 item_4_id : 8;
  unsigned __int32 item_4_number : 6;
  unsigned __int32 item_5_id : 8;
  unsigned __int32 item_5_number : 6;
  u8 character;
  u8 levelSword;
  u8 levelLance;
  u8 levelAxe;
  u8 levelBow;
  u8 levelStaff;
  u8 levelAnima;
  u8 levelLight;
  u8 levelDark;
  u8 levelSupport[7];
};

/* 213 */
typedef struct UnitDataInSave UnitInSave;

/* 214 */
struct ROMItemEntry;

/* 215 */
struct BattleStatsStruct;

/* 216 */
struct TrapStruct;

/* 217 */
struct UnitStruct;

/* 218 */
struct ChapterDataStruct;

/* 219 */
struct UnitWordStruct;

/* 220 */
struct ROMUnitEntry;

/* 221 */
struct ROMClassEntry;

/* 222 */
enum FlagsCAttr
{
  CAttrNone = 0x0,
  CAttrMountedAid = 0x1,
  CAttrCanto = 0x2,
  CAttrSteal = 0x4,
  CAttrLockpick = 0x8,
  CAttrDance = 0x10,
  CAttrPlay = 0x20,
  CAttrCritBonus = 0x40,
  CAttrBallista = 0x80,
  CAttrPromoted = 0x100,
  CAttrSupply = 0x200,
  CAttrMounted = 0x400,
  CAttrWyvern = 0x800,
  CAttrPegasus = 0x1000,
  CAttrLord = 0x2000,
  CAttrFemale = 0x4000,
  CAttrBoss = 0x8000,
  CAttrLock1 = 0x10000,
  CAttrLock2 = 0x20000,
  CAttrLock3 = 0x40000,
  CAttrMaxLevel10 = 0x80000,
};

/* 223 */
enum FlagsIAttr
{
  IAttrNone = 0x0,
  IAttrWeapon = 0x1,
  IAttrMagic = 0x2,
  IAttrStaff = 0x4,
  IAttrUnbreakable = 0x8,
  IAttrUnsellable = 0x10,
  IAttrBrave = 0x20,
  IAttrMagicDamage = 0x40,
};

/* 224 */
struct BattleUnitStruct;

/* 225 */
struct ActionStruct;

/* 226 */
struct EventDataPtr;

/* 227 */
struct WMLocationStruct;

/* 228 */
struct ArenaStruct;

/* 229 */
struct PrepListItemStruct;

/* 230 */
enum HardcodedTextId
{
  HammerneUseHelpText = 0x878,
};

/* 231 */
struct Header6C;

/* 232 */
enum Construct6CCodes
{
  _END = 0x0,
  _SET_NAME = 0x1,
  _CALL = 0x2,
  _LOOP = 0x3,
  _SET_DESTRUCTOR = 0x4,
  _ADD_CHILD = 0x5,
  _ADD_CHILD_BLOCKING = 0x6,
  _ADD_MAIN = 0x7,
  _BLOCK_WHILE_EXISTS = 0x8,
  _DELETE_EACH = 0x9,
  _BREAK_EACH = 0xA,
  _LABEL = 0xB,
  _GOTO = 0xC,
  _JUMP = 0xD,
  _SLEEP = 0xE,
  _MARK = 0xF,
  _BLOCK = 0x10,
  _DELETE_IF_DUPLICATE = 0x11,
  _SET_BIT4 = 0x12,
  _13 = 0x13,
  _BLOCK_WHILE = 0x14,
  _15 = 0x15,
  _CALLR_AND_MAYBE_YIELD = 0x16,
  _DELETE_EACH_DUPLICATE = 0x17,
  _CALLR_ARG = 0x18,
  _19 = 0x19,
};

/* 233 */
struct State6CBB;

/* 234 */
struct SomeInternal6CBBStruct;

/* 235 */
struct TextStruct;

/* 236 */
struct EventEngine6C;

/* 237 */
struct MenuCommandStruct;

/* 238 */
struct AIStruct;

/* 239 */
struct OAMInterBufferStruct;

/* 240 */
struct KeyBuffer;

/* 241 */
struct MovementFillStruct;

/* 242 */
struct RTextStruct;

/* 243 */
enum SpellAssocFacing
{
  SAF_Target = 0x0,
  SAF_Up = 0x1,
  SAF_Right = 0x2,
  SAF_Standing = 0x3,
};

/* 244 */
struct BattleAnimStruct;

/* 245 */
struct UnitEventStruct;

/* 246 */
struct TCS;

/* 247 */
struct GmapUnit6C;

/* 248 */
struct MapAnimMasterStruct;

/* 249 */
struct MOVEUNIT6C;

/* 250 */
struct Vector2H;

/* 251 */
struct BWLEntry;

/* 252 */
struct PromotionInit6C;

/* 253 */
struct PromotionMain6C;

/* 254 */
struct PromotionSub6C;

/* 255 */
struct TileBufferEntry;

/* 256 */
struct IconInfoStruct;

/* 257 */
struct FontStruct;

/* 258 */
struct TextGlyphHeader;

/* 259 */
struct MOVEUNITExtraData;

/* 260 */
struct DebugTextStruct;

/* 261 */
struct EventEngineCallEntryStruct;

/* 262 */
struct BattleAnimUnitStruct;

